import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/Providers";
import NavBar from "@/components/common/Nav/Navbar";
import Footer from "@/components/common/Footer/Footer";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <NextThemesProvider attribute="class" defaultTheme="light">

          <NavBar />
          <Toaster position="bottom-center" />

        {children}
        {/* <Footer /> */}
        </NextThemesProvider>
        </Providers>
        
        </body>
    </html>
  );
}
